### ISSUE TITLE
System.ArgumentException - error on retrieving deployed env variables that refer to another env variable

### ISSUE THREAD

**Issue by i348620** [Azure/Bridge-To-Kubernetes#151]
**Describe the bug**

I am trying to use Bridge to Kubernetes to debug a deployed service.

As part of that service's config I am using the following concept of referring to an environment variable in my config
![image](https://user-images.githubusercontent.com/115151150/214318434-640d0a8b-bbb9-4eec-8218-5f815d7aa659.png)

My config within the tasks.json "useKubernetesServiceEnvironmentVariables" is set to "true" as I understand it is necessary for remote debugging.

In my case these are the config/env variables I am using:
![image](https://user-images.githubusercontent.com/115151150/214319887-32242177-e3a1-41b4-adbc-5008bf595556.png)

This then throws an error :

>  *  Executing task: bridge-to-kubernetes.resource 

Redirecting Kubernetes service application-parameter-service to your machine...
Target cluster: xx
Current cluster: xx
Target namespace: platform
Current namespace: platform
Target service name: application-parameter-service
Target service ports: 80
Using kubernetes service environment variables: true

Retrieving the current context and credentials...
Validating the credentials to access the cluster...
Validating the requirements to replicate resources locally...
Redirecting traffic from the cluster to your machine...
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key:   "clientsecret": "XX"
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.BridgeToKubernetes.Common.Kubernetes.KubernetesClient.<>c__DisplayClass73_0.<GetContainerEnvironmentAsync>b__0(String output)
   at Microsoft.BridgeToKubernetes.Common.Kubernetes.KubectlImpl.<>c__DisplayClass9_1.<RunShortRunningCommand>b__1(Object sender, DataReceivedEventArgs e)
   at Microsoft.BridgeToKubernetes.Common.IO.ProcessEx.<.ctor>b__1_0(Object o, DataReceivedEventArgs e)
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

As an additional information,
I have tried to remove the "VCAP_SERVICES" environment variable that makes a reference to the two env vars above using $() and the service has started successfully. Although it won't work as a workaround for me as I need all of the config values.

I am hoping there might be some sort of config that will allow values that seem to have "duplicate keys" or something else that will help me deal with this error.

Any help is greatly appreciated, thank you in advance!

**Mention the platform you are using**
VSCode

**Expected behavior**
I am expecting for the environment variables to be correctly duplicated onto my local environment and the server to start on my desktop.

**Desktop (please complete the following information):**
- VSCode on WSL2

**Additional context**

**Comment by elenavillamil** [comment]
Hi @i348620 ! Thank you for the detailed issue :) Have you tried actually using bridge after it connects without VCAP_SERVICE? I think it will work. Reason why is because when user uses remote debugging (aka useKubernetesServiceEnvironmentVariables) it means we cannot ask for elevated access and edit host files, so instead bridge sets environment variables to set up the traffic forwarding (the exact kubernetes concept you mentioned in the issue). Long answer short, bridge will be setting VCAP_SERVICE environment variable to work as you expect. Can you give it a try and tell me if that is the case? 

On side note for our team, we should do a change in bridge to were above fails gracefully instead of crashing.

**Comment by elenavillamil** [comment]
Closing due to inactivity plus please feel free to re-open if needed.
