### ISSUE TITLE
Is k3s on raspberry os supported (raspberry pi 4/8 GB)?

### ISSUE THREAD

**Issue by zljubisic** [Azure/Bridge-To-Kubernetes#291]
Type: <b>Bug</b>

I have an raspberry pi 4 (8 GB of ram) with raspberry pi os installed.

```
$ uname -a
Linux rpi4 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux

```

Using vscode on my windows computer i connected to the host rpi4 and installed bridge on kubernetes there. Now on rpi4, using vscode side bar's Kubernetes icon I can see k3s kubernetes cluster, its pods, services and so on.
As we know k3s installs its kubectl in /usr/local/bin/kubectl.

When I (ctrl+shift+P) execute "Bridge to kubernetes: Configure" I am asked to select the service, but nothing is offered to me. At the same time Kubernetes in vscode status line has triangle with exclamation inside of it.

Output of Bridge to kubernetes shows:

```
Bridge to Kubernetes initialization (VS Code v1.79.2 - Extension v2.0.120230525)
Logs: /home/pi/.vscode-server/data/logs/20230701T171852/exthost4/mindaro.mindaro/mindaro-vscode-2023-07-01T15-21-34.311Z.txt
```
In this file, last few lines look like this:

```
2023-07-01T15:22:38.543Z | Common Extension Root    | TRACE | Extension activated successfully <json>{"remoteName":"ssh-remote"}</json>
2023-07-01T15:22:38.545Z | Common Extension Root    | TRACE | Event: kubectl-client-command <json>{"args":"version --short --client -o json","remoteName":"ssh-remote"}</json>
2023-07-01T15:22:38.585Z | Common Extension Root    | ERROR | Error: cli-client-get-version-error <json>{"remoteName":"ssh-remote"}</json> <stack>Error: /home/pi/.vscode-server/data/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/dsc: 1: cannot open �: No such file\n/home/pi/.vscode-server/data/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/dsc: 2: v: not found\n/home/pi/.vscode-server/data/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/dsc: 1: ^?ELF^B^A^A^C^C: not found\n/home/pi/.vscode-server/data/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/dsc: 4: ^Q�^P^R�: not found\n/home/pi/.vscode-server/data/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/dsc: 5: ^Q5^F^R^R
^S: not found\n/home/pi/.vscode-server/data/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/dsc: 3: v^P^A^FX^W^BX^BX^Bi\n�\n^P^B^F�^W^B�^B�^BP^BP^B^H^D^D�^B�^B�^BDD^D^G^DX^W^BX^BX^B^H^HP�td^D�^A�^A�^A�^N�^N^DQ�td^F^PR�td^DX^W^BX^BX^B^A/lib64/ld-linux-x86-64.so.2^D^T^CGNU: not found\n/home/pi/.vscode-server/data/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/dsc: 6: ^R: not found\n/home/pi/.vscode-server/data/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/dsc: 7: ^Q-^Q^R�^L^Q*^B^R�^F^R.^R: not found\n/home/pi/.vscode-server/data/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/dsc: 8: ^Q�\n^Q�\n^Qq^B^Rh^G^R^Q: not found\n/home/pi/.vscode-server/data/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/dsc: 8: ^Q^R4^G^R�^P^R^A^A^R�^Q^RT^D^R�^O^Ri^P^R-: not found\n/home/pi/.vscode-server/data/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/dsc: 10: ^B^C^C^F^C^B^B^F^B^B^B: not found\n/home/pi/.vscode-server/data/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/dsc: 11: y^K^K�^Q^A^A�^P: not found\n/home/pi/.vscode-server/data/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/dsc: 11: ^B^H^B^B^C^B^B^B^F^B^C^H^B^H^F^B^B^B^C^B^C^B^C^D^F^D^B^B^F^B^B^K^C^B^B^C^D^B^B^L^B^D^C^B^C^B^C^C^C^A^A�^O^P: not found\n/home/pi/.vscode-server/data/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/dsc: 12: Syntax error: ")" unexpected\n\n  at ChildProcess.<anonymous> (/home/pi/.vscode-server/extensions/mindaro.mindaro-2.0.120230525/dist/extension.js:2:845153)\n     at ChildProcess.emit (node:events:513:28)\n     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)</stack>
2023-07-01T15:22:38.591Z | Common Extension Root    | ERROR | Error: kubectl-client-command-error <json>{"args":"version --short --client -o json","remoteName":"ssh-remote"}</json> <stack>Error: \n   at ChildProcess.<anonymous> (/home/pi/.vscode-server/extensions/mindaro.mindaro-2.0.120230525/dist/extension.js:2:845153)\n     at ChildProcess.emit (node:events:513:28)\n     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)</stack>
2023-07-01T15:22:38.596Z | Common Extension Root    | ERROR | Error: kubectl-client-get-version-error <json>{"remoteName":"ssh-remote"}</json> <stack>Error: \n at ChildProcess.<anonymous> (/home/pi/.vscode-server/extensions/mindaro.mindaro-2.0.120230525/dist/extension.js:2:845153)\n     at ChildProcess.emit (node:events:513:28)\n     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)</stack>
2023-07-01T15:32:51.167Z | Common Extension Root    | TRACE | Event: configure-command-triggered <json>{"remoteName":"ssh-remote"}</json>
2023-07-01T15:32:51.172Z | Connect (bridge/83e08639 | TRACE | Event: connect-wizard-start <json>{"wizardReason":"ConfigurationCommand","type":"service","remoteName":"ssh-remote"}</json>
2023-07-01T15:32:51.179Z | Common Extension Root    | WARNG | Event: binaries-utility-try-get-binaries-error <json>{"remoteName":"ssh-remote"}</json>
2023-07-01T15:32:51.180Z | Common Extension Root    | WARNG | Event: binaries-utility-try-get-binaries-error <json>{"remoteName":"ssh-remote"}</json>
2023-07-01T15:32:51.182Z | Connect (bridge/83e08639 | TRACE | Event: connect-wizard-stop <json>{"wizardReason":"ConfigurationCommand","type":"service","isWizardComplete":false,"isResourceNameSet":"false","isIsolateAsSet":"false","isTargetClusterSet":"false","isTargetNamespaceSet":"false","isCreatingNewLaunchConfiguration":false,"remoteName":"ssh-remote"}</json>
```
I also saw in output of File Downloader this:

```
File Downloader extension now active.
Starting download from https://bridgetokubernetes.blob.core.windows.net/zipv2/LKS/dotnetruntime-linux.zip
Starting download from https://bridgetokubernetes.blob.core.windows.net/zipv2/LKS/kubectl-linux.zip
Starting download from https://bridgetokubernetes.blob.core.windows.net/zipv2/1.0.20230525.1/lpk-linux.zip
```

Why Bridge to kubernetes is downloading kubectl if there is one already installed?
For example, if I go to the folder: /home/pi/.vscode-server/data/User/globalStorage/mindaro.mindaro/file-downloader-downloads/bridge/kubectl/linux and exexcute:

```
$ file kubectl
kubectl: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped

```
why x86-64 architecture?

Does Bridge to kubernetes work in setup I have described?
Is there any workaround?

Extension version: 2.0.120230525
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux arm64 5.15.84-v8+

**Comment by zljubisic** [comment]
@hsubramanianaks Hi, logs are not in `/tmp/Bridge To Kubernetes` but I have found some in:

```
./data/logs/20230708T090628/exthost1/output_logging_20230708T090634/7-Bridge to Kubernetes.log
./data/logs/20230701T171852/exthost3/output_logging_20230701T171920/5-Bridge to Kubernetes.log
./data/logs/20230701T171852/exthost4/output_logging_20230701T171957/7-Bridge to Kubernetes.log
./data/logs/20230701T171852/exthost1/output_logging_20230701T171912/9-Bridge to Kubernetes.log
./data/logs/20230701T171852/exthost2/output_logging_20230701T171916/9-Bridge to Kubernetes.log
./data/logs/20230702T143813/exthost1/output_logging_20230702T143829/7-Bridge to Kubernetes.log
./data/logs/20230702T143813/exthost2/output_logging_20230702T151000/7-Bridge to Kubernetes.log
./data/logs/20230630T165947/exthost3/output_logging_20230630T171909/8-Bridge to Kubernetes.log
./data/logs/20230630T165947/exthost4/output_logging_20230630T173435/9-Bridge to Kubernetes.log
./data/logs/20230630T165947/exthost2/output_logging_20230630T170025/9-Bridge to Kubernetes.log
./data/logs/20230630T165947/exthost5/output_logging_20230630T174143/9-Bridge to Kubernetes.log
./data/logs/20230706T232307/exthost1/output_logging_20230706T232312/7-Bridge to Kubernetes.log
./data/logs/20230701T093646/exthost3/output_logging_20230701T094411/9-Bridge to Kubernetes.log
./data/logs/20230701T093646/exthost5/output_logging_20230701T094244/7-Bridge to Kubernetes.log
```

Is that what you are looking for?

**Comment by hsubramanianaks** [comment]
@zljubisic these are vscode extension logs, you can share them as well. I am looking for CLI logs for example: in ubuntu via WSL2 it would be in location ```\\wsl.localhost\Ubuntu\tmp\Bridge To Kubernetes``` sometimes it could be in your ```$HOME\tmp\Bridge To Kubernetes```. Please check these possible locations. Basically B2K would write the logs to Operating system's temp folder\Bridge To Kubernetes folder. Thank you.

**Comment by zljubisic** [comment]
@hsubramanianaks As I explained in my very first post I am running VSCode on Windows 10 and than from it connect to host rpi4 on Raspbian OS.
On rpi4, there is no `/tmp/Bridge*` nor `$HOME\tmp\Bridge*` directory.
