### ISSUE TITLE
Bridge to Kubernetes VS Code Extension fails to install Kubernetes dependencies

### ISSUE THREAD

**Issue by Hopp3r** [Azure/Bridge-To-Kubernetes#326]
**Describe the bug**
VS Code plugin fails to install dependencies.
Attempts to manually install following this closed issue (and recommended solution by the extension) fails:
https://github.com/microsoft/mindaro/issues/32

**Mention the platform you are using**
I'm running a completely fresh install of Sonoma 14.0 on an M2 Pro Mac mini.

**To Reproduce**
1. Install VS Code
2. Install Bridge to Kubernetes Extension
3. Notice failure installing dependencies:
 a. "Failed to update dependencies: Failed to retrieve dotnet runtime version: spawn Unknown system error -86
 b. Open mindaro log: 
     ```
        023-10-09T10:44:26.136Z | Common Extension Root    | TRACE | Successfully determined the dotnetruntime binary path: /Users/daniel/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/dotnet <json>{}</json>
        2023-10-09T10:44:26.448Z | Common Extension Root    | ERROR | Error: dotnet-client-get-version-error <json>{}</json> <stack>Error: spawn Unknown system error -86\n	at ChildProcess.spawn (node:internal/child_process:413:11)\n	at spawn (node:child_process:817:9)\n	at t.CommandRunner.<anonymous> (/Users/daniel/.vscode/extensions/mindaro.mindaro-2.0.120231004/dist/extension.js:2:586282)\n	at Generator.next (<anonymous>)\n	at /Users/daniel/.vscode/extensions/mindaro.mindaro-2.0.120231004/dist/extension.js:2:585790\n	at new Promise (<anonymous>)\n	at n (/Users/daniel/.vscode/extensions/mindaro.mindaro-2.0.120231004/dist/extension.js:2:585535)\n	at t.CommandRunner.runAsync (/Users/daniel/.vscode/extensions/mindaro.mindaro-2.0.120231004/dist/extension.js:2:586089)\n	at t.DotNetClient.<anonymous> (/Users/daniel/.vscode/extensions/mindaro.mindaro-2.0.120231004/dist/extension.js:2:587817)\n	at Generator.next (<anonymous>)\n	at /Users/daniel/.vscode/extensions/mindaro.mindaro-2.0.120231004/dist/extension.js:2:587404\n	at new Promise (<anonymous>)\n	at n (/Users/daniel/.vscode/extensions/mindaro.mindaro-2.0.120231004/dist/extension.js:2:587149)\n	at e (/Users/daniel/.vscode/extensions/mindaro.mindaro-2.0.120231004/dist/extension.js:2:587748)\n	at t.RetryUtility.<anonymous> (/Users/daniel/.vscode/extensions/mindaro.mindaro-2.0.120231004/dist/extension.js:2:662717)\n	at Generator.next (<anonymous>)\n	at /Users/daniel/.vscode/extensions/mindaro.mindaro-2.0.120231004/dist/extension.js:2:662530\n	at new Promise (<anonymous>)\n	at r (/Users/daniel/.vscode/extensions/mindaro.mindaro-2.0.120231004/dist/extension.js:2:662275)\n	at t.RetryUtility.retryAsync (/Users/daniel/.vscode/extensions/mindaro.mindaro-2.0.120231004/dist/extension.js:2:662666)\n	at t.RetryUtility.<anonymous> (/Users/daniel/.vscode/extensions/mindaro.mindaro-2.0.120231004/dist/extension.js:2:662801)\n	at Generator.next (<anonymous>)\n	at s (/Users/daniel/.vscode/extensions/mindaro.mindaro-2.0.120231004/dist/extension.js:2:662332)</stack>
        2023-10-09T10:44:26.448Z | Common Extension Root    | WARNG | Encountered error running get version on dotnetruntime: Failed to retrieve dotnet runtime version: spawn Unknown system error -86 <json>{"clientType":"dotnetruntime"}</json>
    ``` 
4. Follow instructions on this issue:  https://github.com/microsoft/mindaro/issues/32
   a. as per suggestions in the comments - I used the same version url as listed in the error log: https://bridgetokubernetes.blob.core.windows.net/zipv2/1.0.20231003.1/lks.json

5. Notice the same issue occurs.

**Expected behavior**
Kubernetes dependencies should be installed correctly & automatically by the extension.

**Desktop (please complete the following information):**
 - OS: Sonoma 14
 - Version: v2.0.120231004

**Comment by hsubramanianaks** [comment]
@Hopp3r we have open issue https://github.com/Azure/Bridge-To-Kubernetes/issues/273 where b2k has issue with running in arm based machines/clusters (we are working on them to get it fixed here is the [PR](https://github.com/Azure/Bridge-To-Kubernetes/pull/290)). But as a work around can you try downloading latest dotnet for Mac OS arm (.NET 7.0.11 ) - [here](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-7.0.11-macos-arm64-binaries) and move the binaries to ```/Users/daniel/Library/Application Support/Code/User/globalStorage/mindaro.mindaro/file-downloader-downloads/dotnet/dotnet``` and try using bridge. Meanwhile I will try it myself and keep you posted on the fix. Thank you.

**Comment by anuprshetty** [comment]
I am getting Failed to update dependencies error in vs code.

vs code version: 1.85.1
bridge to kubernetes version: v2.0.120231128
mac version: 14.1.1 (23B81)

NOTE: I have also installed 

> dsc cli

 based on this repo's readme documentation.
Link: https://github.com/Azure/Bridge-To-Kubernetes#cli-tool-installation
Install command: curl -fsSL https://raw.githubusercontent.com/Azure/Bridge-To-Kubernetes/main/scripts/install.sh | bash

Error screenshot:
<img width="544" alt="screenshot 2023-12-14 at 7 49 22 PM" src="https://github.com/Azure/Bridge-To-Kubernetes/assets/47313445/c027d00d-af43-4381-a4e2-960babb93e15">

**Comment by hsubramanianaks** [comment]
@anuprshetty If you are using arm64 or M1 mac this is known issue, we are working on a fix and I can update here once it is merged and released. Thank you for your patience.

**Comment by anuprshetty** [comment]
@hsubramanianaks Thanks for the response. 

**Quick update:** I am using arm64 - M2 mac. So M2 mac also has the same problem.
