### ISSUE TITLE
Support to use "localhost" instead of 127.0.0.1 when accessing other services

### ISSUE THREAD

**Issue by larsf96** [Azure/Bridge-To-Kubernetes#347]
**Is your feature request related to a problem? Please describe.**
Currently all services that are requested in KubernetesLocalProcessConfig.yaml are exposed via 127.0.0.1.
This is causing problems with (for example) Kafka as Kafka requires a hostname to be present. Using "localhost" instead of 127.0.0.1 would work in this case, but I don't see any option how to configure this

**Mention what platform you want to support the new feature**
All platforms

**Describe the solution you'd like**
It would be helpful if a DNS name could be specified that can be used instead of the local IP 127.0.0.1

**Additional context**
```
Caused by: org.apache.kafka.common.config.ConfigException: Invalid url in bootstrap.servers: 127.0.0.1
        at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:71) ~[kafka-clients-3.6.1.jar:na]
        at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:60) ~[kafka-clients-3.6.1.jar:na]
        at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:56) ~[kafka-clients-3.6.1.jar:na]
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:707) ~[kafka-clients-3.6.1.jar:na]
        ... 27 common frames omitted
```

**Comment by Vidya2606** [comment]
@larsf96 Thanks for raising this issue. We will check and get back to you.
